services:
  redis-db:
    container_name: redis-db
    hostname: redis-db
    image: redis:8.0-rc1
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
        